# Generated by Django 6.0.5 on 2026-05-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_upipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('banner_top', 'Top Banner'), ('sidebar', 'Sidebar'), ('inline', 'Article Inline'), ('banner_bottom', 'Bottom Banner')], default='banner_top', max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
