# Generated by Django 6.0.5 on 2026-05-26 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_payment_options_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='news.district')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='news.state'),
        ),
        migrations.CreateModel(
            name='FetchedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(unique=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='India', max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='en', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.block')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.district')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.state')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['state', '-published_at'], name='news_fetche_state_i_bc89ce_idx'), models.Index(fields=['district', '-published_at'], name='news_fetche_distric_44f97a_idx'), models.Index(fields=['category', '-published_at'], name='news_fetche_categor_9d8f71_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'name')},
        ),
    ]
